# Generated by Django 6.0.2 on 2026-02-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpiada', '0002_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
