# Generated by Django 6.0.2 on 2026-02-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpiada', '0003_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('file', models.FileField(upload_to='tests/')),
            ],
        ),
    ]
