# Generated by Django 6.0.2 on 2026-02-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpiada', '0004_testmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmaterial',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
