# Generated by Django 6.0.2 on 2026-02-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpiada', '0005_alter_testmaterial_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
