# Generated by Django 6.0.2 on 2026-02-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpiada', '0006_alter_student_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('grade', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('correct_count', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('score_percent', models.FloatField()),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('user_answers', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='testmaterial',
            name='file',
            field=models.FileField(upload_to='tests/'),
        ),
    ]
