# Generated by Django 6.0.2 on 2026-02-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpiada', '0007_testresult_alter_testmaterial_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='test_material_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
