# Generated by Django 6.0.2 on 2026-02-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpiada', '0008_testresult_test_material_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='questions_order',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
