# Generated by Django 6.0.2 on 2026-03-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpiada', '0009_testresult_questions_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField(default=30)),
                ('test_duration', models.IntegerField(default=60)),
                ('retry_attempts', models.IntegerField(default=1)),
            ],
        ),
    ]
