# Generated by Django 6.0.2 on 2026-03-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpiada', '0011_student_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='retry_attempts',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_points',
            field=models.IntegerField(default=4),
        ),
    ]
