# Generated by Django 6.0.2 on 2026-03-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpiada', '0012_remove_systemsettings_retry_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='optional_subjects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
