# Generated by Django 6.0.2 on 2026-03-30 04:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpiada', '0014_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device', models.CharField(default='Kompyuter', max_length=30)),
                ('browser', models.CharField(default='Boshqa', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='olimpiada.student')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi seansi',
                'verbose_name_plural': 'Foydalanuvchi seanslari',
                'ordering': ['-last_activity'],
            },
        ),
    ]
